server:
  port: 8080
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
