server:
  port: 8080
#  ssl:
#    key-store-password: password
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
spring:
  data:
    mongodb:
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
            - public_profile
            - email
            - user_friends

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO