spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: airportmanagement
      username: root
      password: pass
      auto-index-creation: true
#      uri: mongodb://root:pass@mongo:27017/airportmanagement # SHORT HAND

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG